POST http://localhost:3000/api/account
Content-Type: application/json

{
    "name": "apalah",
    "username": "apalah",
    "email": "andikaasda@gmail.com",
    "password": "adachikawai",
    "image": "/defaultpp.webp",
    "role": "teacher"
}

###
GET http://localhost:3000/api/account?n=bangdik

###
DELETE http://localhost:3000/api/account?n=bangdik