POST http://localhost:3000/api/account
Content-Type: application/json

{
    "name": "",
    "email": "andikaasda@gmail.com",
    "password": "adachikawai",
    "image": "/defaultpp.webp",
    "role": "teacher"
}

###
GET http://localhost:3000/api/account

###
DELETE http://localhost:3000/api/account?v=662711eee62da802cb3ddaf0