import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthProvider } from "./AuthProvider";

export const metadata: Metadata = {
  title: "zaloid",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: any) {
  return (
    <html className="bg-black">
      <AuthProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </AuthProvider>
    </html>
  );
}
