GET http://localhost:3000/api/kelas?c=66b0cd4a7c7910f8a1c3b69b

###
POST http://localhost:3000/api/account
Content-Type: application/json

{
    "label" : "kelas jawa",
    "teachersRef": ["66ae19b12c485b82d75f26f4"]
}