GET http://localhost:3000/api/kelas?c=66b7bb61716a479e9c023fe9

###
POST http://localhost:3000/api/account
Content-Type: application/json

{
    "label" : "kelas jawa",
    "teachersRef": ["66ae19b12c485b82d75f26f4"]
}